### ISSUE TITLE
Consolidate Type Inference, Schema, Stats Utility 

### ISSUE THREAD

**Issue by kanitw** [uwdata/compassql#103]
Given a dataset, we want a simple method that provides us both Schema and Stats

(For reference see https://github.com/vega/vega-editor/blob/compassql/app/editor.js#L301 for older way to do it.) 
```ts
Schema.build(data: any /*actual data*/): Schema // the new Schema consolidate `Schema` and `Stats`
``` 

- [x] consolidate `Schema` and `Stats`
- [x] For each field, first calculate `summary` with `dl.summary` to raw stats
- [x] From stats, infer type of measurement to create `FieldSchema` (#88)
- [x] update editor.js with the new API

tips: you might wanna use data from `vega-datasets` module

## Later 

- [ ] Set number field to ordinal if cardinality is low (#88) 
- [ ] make sure we correct infer date (#91 -- later)
- [ ] Make sure we correctly infer primitive type (#116)
  - [ ] deal with an issue where the first item is null (I believe somehow it infers `number | date` as `string` if the first is null -- at least back then)
- [ ] Add Stats Calculation for binned Q fields and T fields with timeUnit  (#95)
- [ ] allow ordering (#108)

**Comment by kanitw** [comment]
Let's close this as we already have separate issues for the required follow-ups.
