### ISSUE TITLE
Add Post Enumeration Modification / Transform to `generate.ts`

### ISSUE THREAD

**Issue by kanitw** [uwdata/compassql#176]
Instead of returning answerSet, add a logic that can transform the `specQuery` in the `specQueryModel`  (apply `map` to `answerSet` in generate.ts if one of the modifier/stylizer is included.).

(We currently have a hack for these in [`vlplot.js`](https://github.com/vega/vega-lite-ui/blob/master/src/components/vlplot/vlplot.js#L149), but it should be migrated here.) 

A few configs to be added for the transforms

- [x] `smallBandSizeForHighCardinality: {maxCardinality: number, bandSize: number}` #93
- [x] `smallBandSizeForFacet: {maxCardinality: number, bandSize: number}` #93 
- [x] `nominalScaleForHighCardinality` #101
- [ ] `xAxisOnTopForHighYCardinalityWithoutColumn`:   {maxCardinality: number}` -- require #92

---- 
(**LATER**)

- [ ] Support taking generic stylizer as input
